choco install -y googlechrome
choco install -y git
choco install -y tortoisegit
choco install -y dotnetcore-sdk
choco install -y nodejs
choco install -y vscode
choco install -y visualstudio2017community
choco install -y gnuwin32-coreutils.install
choco install -y curl